
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username": "john",
    "password": "john"
}

### 

DELETE http://localhost:5000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjY2MDk2Njg0LCJleHAiOjE2NjYwOTY3ODR9.t_Cx1-9_YP6S8sA3PEwT622z3i7RUGPFYbob9epUa7s

###
POST http://localhost:5000/api/logout
Content-Type: application/json
{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjY2MDk2Njg0LCJleHAiOjE2NjYwOTY3ODR9.t_Cx1-9_YP6S8sA3PEwT622z3i7RUGPFYbob9epUa7s"
}

###
POST http://localhost:5000/api/refresh
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjY2MDk2Njg0LCJleHAiOjE2NjYwOTY3ODR9.t_Cx1-9_YP6S8sA3PEwT622z3i7RUGPFYbob9epUa7s"
}